Repository inventree/inventree-docs, pull requests merged in 2023-01, with the labels that each got.

#418 Add documentation for SSO callback URL
  docs/settings/SSO.md
Labels: documentation

#419 Changes for SSO
  docs/settings/SSO.md
  docs/settings/global.md
Labels: enhancement

#423 Added variables for stock location
  docs/report/context_variables.md
Labels: documentation, enhancement
